# Dockerfile.rasa
# Builds the main Rasa server

# FROM rasa/rasa:latest
# FROM rasa/rasa:3.6.10
docker pull rasa/rasa
WORKDIR /app
COPY . /app
USER rasa
# Render provides a PORT env var we must use.
CMD ["run", "--enable-api", "--cors", "*", "--port", "$PORT"]