FROM rasa/rasa-sdk:latest
WORKDIR /app
COPY actions/ /app/actions
COPY requirements.txt .
USER root
RUN pip install --no-cache-dir -r requirements.txt
USER 1001
CMD ["start", "--actions", "actions", "--port", "$PORT", "--debug"]