# Dockerfile.actions
# Using the 'latest' tag for the SDK, as specific patch versions are not published.
# This is the stable, compatible SDK for all recent 3.x Rasa versions.
FROM rasa/rasa-sdk:latest

WORKDIR /app
COPY actions/ /app/actions
COPY requirements.txt .
USER root
RUN pip install --no-cache-dir -r requirements.txt
USER 1001
CMD ["start", "--actions", "actions", "--port", "$PORT"]