# Dockerfile.rasa (Gunicorn Version)

FROM rasa/rasa:3.6.10
WORKDIR /app

# Copy requirements first to leverage Docker layer caching
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the project
COPY . .

# The entrypoint.sh script will be run when the container starts.
ENTRYPOINT ["./entrypoint.sh"]